// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKbp2ivUGlbHJSsCY9-6IWTDbnuVFwENM',
    appId: '1:714529153818:web:05f1911d9ced48904d82a3',
    messagingSenderId: '714529153818',
    projectId: 'tester-5f37b',
    authDomain: 'tester-5f37b.firebaseapp.com',
    storageBucket: 'tester-5f37b.firebasestorage.app',
    measurementId: 'G-6DTYMZNL7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_Yy3LsOjtAanwH-lICYiJnaJ38x_t9PM',
    appId: '1:714529153818:android:2a209c850a07e5154d82a3',
    messagingSenderId: '714529153818',
    projectId: 'tester-5f37b',
    storageBucket: 'tester-5f37b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7TXgBN-INmPU8KAQTS-fcu8rv4oOJAFQ',
    appId: '1:714529153818:ios:7d678b0853c376414d82a3',
    messagingSenderId: '714529153818',
    projectId: 'tester-5f37b',
    storageBucket: 'tester-5f37b.firebasestorage.app',
    iosBundleId: 'com.example.fb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7TXgBN-INmPU8KAQTS-fcu8rv4oOJAFQ',
    appId: '1:714529153818:ios:7d678b0853c376414d82a3',
    messagingSenderId: '714529153818',
    projectId: 'tester-5f37b',
    storageBucket: 'tester-5f37b.firebasestorage.app',
    iosBundleId: 'com.example.fb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKbp2ivUGlbHJSsCY9-6IWTDbnuVFwENM',
    appId: '1:714529153818:web:5c3364a024e8f5794d82a3',
    messagingSenderId: '714529153818',
    projectId: 'tester-5f37b',
    authDomain: 'tester-5f37b.firebaseapp.com',
    storageBucket: 'tester-5f37b.firebasestorage.app',
    measurementId: 'G-RZWF6ZG5XV',
  );
}
